# Generated by Django 3.1.7 on 2021-03-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='national_code',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
