# Generated by Django 3.1.7 on 2021-04-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210412_1753'),
        ('account', '0002_auto_20210403_1824'),
    ]

    operations = [
    ]
