# Generated by Django 3.2.3 on 2021-05-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
