# Generated by Django 3.2.3 on 2021-05-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
