# Generated by Django 3.1.7 on 2021-03-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210328_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='national_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
