# Generated by Django 3.1.7 on 2021-04-18 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='villas/documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('image', models.ImageField(upload_to='villas/images/')),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('villa_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('Coastal', 'Coastal'), ('Urban', 'Urban'), ('Wild', 'Wild'), ('Mountainous', 'Mountainous'), ('Desert', 'Desert'), ('Rural', 'Rural'), ('Suburban', 'Suburban'), ('Motel', 'Motel')], max_length=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_per_night', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=10, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('area', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('max_capacity', models.IntegerField()),
                ('number_of_bathrooms', models.IntegerField(default=1)),
                ('number_of_bedrooms', models.IntegerField(default=1)),
                ('number_of_single_beds', models.IntegerField(default=1)),
                ('number_of_double_beds', models.IntegerField(default=1)),
                ('number_of_showers', models.IntegerField(default=1)),
                ('documents', models.ManyToManyField(blank=True, to='villa.Document')),
                ('facilities', models.ManyToManyField(blank=True, to='villa.Facility')),
                ('images', models.ManyToManyField(blank=True, to='villa.Image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
