# Generated by Django 3.1.7 on 2021-04-12 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('Coastal', 'Coastal'), ('Urban', 'Urban'), ('Wild', 'Wild'), ('Mountainous', 'Mountainous'), ('Desert', 'Desert'), ('Rural', 'Rural'), ('Suburban', 'Suburban')], max_length=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_per_night', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('area', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('number_of_bathrooms', models.IntegerField(default=1)),
                ('number_of_bedrooms', models.IntegerField(default=1)),
                ('number_of_single_beds', models.IntegerField(default=1)),
                ('number_of_double_beds', models.IntegerField(default=1)),
                ('number_of_showers', models.IntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='villas/images/')),
                ('default', models.BooleanField(default=False)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='villa.villa')),
            ],
        ),
    ]
