# Generated by Django 3.1.7 on 2021-04-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
