# Generated by Django 3.1.7 on 2021-04-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='id',
            new_name='image_id',
        ),
    ]
