# Generated by Django 3.1.7 on 2021-04-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='type',
            field=models.CharField(choices=[('Coastal', 'Coastal'), ('Urban', 'Urban'), ('Wild', 'Wild'), ('Mountainous', 'Mountainous'), ('Desert', 'Desert'), ('Rural', 'Rural'), ('Suburban', 'Suburban'), ('Motel', 'Motel')], max_length=12),
        ),
    ]
