# Generated by Django 3.1.7 on 2021-05-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0002_villa_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(unique=True)),
            ],
        ),
    ]
