# Generated by Django 3.1.7 on 2021-05-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0003_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='rules',
            field=models.ManyToManyField(blank=True, to='villa.Rule'),
        ),
    ]
