# Generated by Django 2.2.12 on 2021-04-27 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account1', to=settings.AUTH_USER_MODEL)),
                ('account2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateTimeField(db_index=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Chat')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parentMessage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.Message')),
            ],
        ),
    ]
